spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: cloud-file-storage

  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:cloud}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:"Qwerty-12345"}

  data:
    redis:
      password: ${REDIS_PASSWORD:redis_simple_pass}

  session:
    timeout: 7d

server:
  servlet:
    session:
      cookie:
        max-age: 30d

logging:
  level:
    org.springframework.session.*: DEBUG
    org.springframework.security.*: DEBUG